# Generated by Django 5.0.5 on 2024-05-22 16:03

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=apps.products.models.product_image_upload_to),
        ),
    ]
