# Generated by Django 5.0.5 on 2024-05-22 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
    ]
