# Generated by Django 5.0.5 on 2024-06-06 16:34

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product_images',
            field=models.ImageField(blank=True, null=True, upload_to=apps.products.models.product_additional_image_upload_to),
        ),
    ]
