services:
  - type: web
    name: nanishop
    env: python
    runtime: python3.11
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn nanishop.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        value: your-secret-key
      - key: DJANGO_SETTINGS_MODULE
        value: nanishop.settings
      - key: DATABASE_URL
        fromDatabase:
          name: your-database-name
          property: connectionString
