services:
  - type: web
    name: nanishop
    env: python
    region: oregon  # Thay bằng region bạn muốn sử dụng
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn nanishop.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        value: django-insecure--&d8+veb4^r*c*7%kt%w3(-*r+7mdvdi^0+t63x^r_4lb_=gfp
      - key: DJANGO_SETTINGS_MODULE
        value: nanishop.settings
      - key: DATABASE_URL
        fromDatabase:
          name: nanishop-db
          property: connectionString
databases:
  - name: nanishop-db
    engine: postgres
    version: 13
    region: oregon  # Thay bằng region bạn muốn sử dụng
    size: small
    diskSize: 10GB
